//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace K12.Sports.FitnessImportExport.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K12.Sports.FitnessImportExport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap amplify_wave_64 {
            get {
                object obj = ResourceManager.GetObject("amplify_wave_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Export_Image {
            get {
                object obj = ResourceManager.GetObject("Export_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Import_Image {
            get {
                object obj = ResourceManager.GetObject("Import_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;學生體適能&quot;&gt;
        ///  &lt;DuplicateDetection&gt;
        ///    &lt;Detector Name=&quot;PrimaryKey1&quot;&gt;
        ///      &lt;Field Name=&quot;學年度&quot; /&gt;
        ///      &lt;Field Name=&quot;身分證字號&quot; /&gt;
        ///    &lt;/Detector&gt;
        ///  &lt;/DuplicateDetection&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field Required=&quot;True&quot; Name=&quot;學年度&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「學年度」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot; /&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「學年度」請輸入數字。&quot; Er [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ImportStudentFitnessRecordVal {
            get {
                return ResourceManager.GetString("ImportStudentFitnessRecordVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap paste_64 {
            get {
                object obj = ResourceManager.GetObject("paste_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;Content&gt;
        ///  &lt;boy&gt;
        ///    &lt;仰臥起坐&gt;
        ///      &lt;!--2020/04/16審查--&gt;
        ///      &lt;!--&lt;_7  請加強=&quot;0,13&quot; 中等=&quot;14,18&quot; 銅牌=&quot;19,23&quot; 銀牌=&quot;24,26&quot; 金牌=&quot;27,99&quot;&gt;&lt;/_7&gt;
        ///      &lt;_8  請加強=&quot;0,15&quot; 中等=&quot;16,21&quot; 銅牌=&quot;22,26&quot; 銀牌=&quot;27,29&quot; 金牌=&quot;30,99&quot;&gt;&lt;/_8&gt;
        ///      &lt;_9  請加強=&quot;0,18&quot; 中等=&quot;19,24&quot; 銅牌=&quot;25,30&quot; 銀牌=&quot;31,33&quot; 金牌=&quot;34,99&quot;&gt;&lt;/_9&gt;--&gt;
        ///      &lt;_10 請加強=&quot;0,18&quot; 中等=&quot;19,24&quot; 銅牌=&quot;25,29&quot; 銀牌=&quot;30,32&quot; 金牌=&quot;33,99&quot;&gt;&lt;/_10&gt;
        ///      &lt;_11 請加強=&quot;0,20&quot; 中等=&quot;21,26&quot; 銅牌=&quot;27,31&quot; 銀牌=&quot;32,34&quot; 金牌=&quot;35,99&quot;&gt;&lt;/_11&gt;
        ///      &lt;_12 請加強=&quot;0,24&quot; 中等=&quot;25,29&quot; 銅牌=&quot;30,34&quot; 銀牌=&quot;35,37&quot; 金牌=&quot;38,99&quot;&gt;&lt;/_12&gt;
        ///      [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Sports_Fitness_Comparison {
            get {
                return ResourceManager.GetString("Sports_Fitness_Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;Content&gt;
        ///  &lt;boy&gt;
        ///    &lt;仰臥起坐&gt;
        ///      &lt;!--&lt;_7  請加強=&quot;0,13&quot; 中等=&quot;14,18&quot; 銅牌=&quot;19,23&quot; 銀牌=&quot;24,26&quot; 金牌=&quot;27,99&quot;&gt;&lt;/_7&gt;
        ///      &lt;_8  請加強=&quot;0,15&quot; 中等=&quot;16,21&quot; 銅牌=&quot;22,26&quot; 銀牌=&quot;27,29&quot; 金牌=&quot;30,99&quot;&gt;&lt;/_8&gt;
        ///      &lt;_9  請加強=&quot;0,18&quot; 中等=&quot;19,24&quot; 銅牌=&quot;25,30&quot; 銀牌=&quot;31,33&quot; 金牌=&quot;34,99&quot;&gt;&lt;/_9&gt;
        ///      &lt;_10 請加強=&quot;0,18&quot; 中等=&quot;19,24&quot; 銅牌=&quot;25,29&quot; 銀牌=&quot;30,32&quot; 金牌=&quot;33,99&quot;&gt;&lt;/_10&gt;
        ///      &lt;_11 請加強=&quot;0,20&quot; 中等=&quot;21,26&quot; 銅牌=&quot;27,31&quot; 銀牌=&quot;32,34&quot; 金牌=&quot;35,99&quot;&gt;&lt;/_11&gt;
        ///      &lt;_12 請加強=&quot;0,24&quot; 中等=&quot;25,29&quot; 銅牌=&quot;30,34&quot; 銀牌=&quot;35,37&quot; 金牌=&quot;38,99&quot;&gt;&lt;/_12&gt;--&gt;
        ///      &lt;_13 請加強=&quot;0,28&quot; 中等=&quot;29,32&quot; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Sports_Fitness_Comparison_103 {
            get {
                return ResourceManager.GetString("Sports_Fitness_Comparison_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 全校體適能中等以上_含中等_各項目百分比統計表 {
            get {
                object obj = ResourceManager.GetObject("全校體適能中等以上_含中等_各項目百分比統計表", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 全校體適能中等以上_含中等_各項目百分比統計表_程式用樣版_ {
            get {
                object obj = ResourceManager.GetObject("全校體適能中等以上_含中等_各項目百分比統計表_程式用樣版_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 班級體適能確認單範本1 {
            get {
                object obj = ResourceManager.GetObject("班級體適能確認單範本1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 體適能個人證明單_功能變數總表1 {
            get {
                object obj = ResourceManager.GetObject("體適能個人證明單_功能變數總表1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 體適能證明單_範本1 {
            get {
                object obj = ResourceManager.GetObject("體適能證明單_範本1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 體適能資料上傳格式 {
            get {
                object obj = ResourceManager.GetObject("體適能資料上傳格式", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 體適能資料上傳格式_xlsx版_ {
            get {
                object obj = ResourceManager.GetObject("體適能資料上傳格式_xlsx版_", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
