//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K12.Sports.FitnessImportExport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K12.Sports.FitnessImportExport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap amplify_wave_64 {
            get {
                object obj = ResourceManager.GetObject("amplify_wave_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Export_Image {
            get {
                object obj = ResourceManager.GetObject("Export_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Import_Image {
            get {
                object obj = ResourceManager.GetObject("Import_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;學生體適能&quot;&gt;
        ///  &lt;DuplicateDetection&gt;
        ///    &lt;Detector Name=&quot;PrimaryKey1&quot;&gt;
        ///      &lt;Field Name=&quot;學年度&quot; /&gt;
        ///      &lt;Field Name=&quot;身分證字號&quot; /&gt;
        ///    &lt;/Detector&gt;
        ///  &lt;/DuplicateDetection&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field Required=&quot;True&quot; Name=&quot;學年度&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「學年度」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot; /&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「學年度」請輸入數字。&quot; Er [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImportStudentFitnessRecordVal {
            get {
                return ResourceManager.GetString("ImportStudentFitnessRecordVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste_64 {
            get {
                object obj = ResourceManager.GetObject("paste_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Content&gt;
        ///	&lt;boy&gt;
        ///		&lt;仰臥起坐&gt;
        ///			&lt;!--2020/04/16審查--&gt;
        ///			&lt;!--&lt;_7  請加強=&quot;0,13&quot; 中等=&quot;14,18&quot; 銅牌=&quot;19,23&quot; 銀牌=&quot;24,26&quot; 金牌=&quot;27,99&quot;&gt;&lt;/_7&gt;
        ///      &lt;_8  請加強=&quot;0,15&quot; 中等=&quot;16,21&quot; 銅牌=&quot;22,26&quot; 銀牌=&quot;27,29&quot; 金牌=&quot;30,99&quot;&gt;&lt;/_8&gt;
        ///      &lt;_9  請加強=&quot;0,18&quot; 中等=&quot;19,24&quot; 銅牌=&quot;25,30&quot; 銀牌=&quot;31,33&quot; 金牌=&quot;34,99&quot;&gt;&lt;/_9&gt;--&gt;
        ///			&lt;_10 請加強=&quot;0,18&quot; 中等=&quot;19,24&quot; 銅牌=&quot;25,29&quot; 銀牌=&quot;30,32&quot; 金牌=&quot;33,99&quot;&gt;&lt;/_10&gt;
        ///			&lt;_11 請加強=&quot;0,20&quot; 中等=&quot;21,26&quot; 銅牌=&quot;27,31&quot; 銀牌=&quot;32,34&quot; 金牌=&quot;35,99&quot;&gt;&lt;/_11&gt;
        ///			&lt;_12 請加強=&quot;0,24&quot; 中等=&quot;25,29&quot; 銅牌=&quot;30,34&quot; 銀牌=&quot;35,37&quot; 金牌=&quot;38,99&quot;&gt;&lt;/_12&gt;
        ///			&lt;_13 請加強=&quot;0,28&quot; 中等=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sports_Fitness_Comparison {
            get {
                return ResourceManager.GetString("Sports_Fitness_Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Content&gt;
        ///  &lt;boy&gt;
        ///    &lt;仰臥起坐&gt;
        ///      &lt;!--&lt;_7  請加強=&quot;0,13&quot; 中等=&quot;14,18&quot; 銅牌=&quot;19,23&quot; 銀牌=&quot;24,26&quot; 金牌=&quot;27,99&quot;&gt;&lt;/_7&gt;
        ///      &lt;_8  請加強=&quot;0,15&quot; 中等=&quot;16,21&quot; 銅牌=&quot;22,26&quot; 銀牌=&quot;27,29&quot; 金牌=&quot;30,99&quot;&gt;&lt;/_8&gt;
        ///      &lt;_9  請加強=&quot;0,18&quot; 中等=&quot;19,24&quot; 銅牌=&quot;25,30&quot; 銀牌=&quot;31,33&quot; 金牌=&quot;34,99&quot;&gt;&lt;/_9&gt;
        ///      &lt;_10 請加強=&quot;0,18&quot; 中等=&quot;19,24&quot; 銅牌=&quot;25,29&quot; 銀牌=&quot;30,32&quot; 金牌=&quot;33,99&quot;&gt;&lt;/_10&gt;
        ///      &lt;_11 請加強=&quot;0,20&quot; 中等=&quot;21,26&quot; 銅牌=&quot;27,31&quot; 銀牌=&quot;32,34&quot; 金牌=&quot;35,99&quot;&gt;&lt;/_11&gt;
        ///      &lt;_12 請加強=&quot;0,24&quot; 中等=&quot;25,29&quot; 銅牌=&quot;30,34&quot; 銀牌=&quot;35,37&quot; 金牌=&quot;38,99&quot;&gt;&lt;/_12&gt;--&gt;
        ///      &lt;_13 請加強=&quot;0,28&quot; 中等=&quot;29,32&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sports_Fitness_Comparison_103 {
            get {
                return ResourceManager.GetString("Sports_Fitness_Comparison_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 全校體適能中等以上_含中等_各項目百分比統計表 {
            get {
                object obj = ResourceManager.GetObject("全校體適能中等以上_含中等_各項目百分比統計表", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 全校體適能中等以上_含中等_各項目百分比統計表_程式用樣版_ {
            get {
                object obj = ResourceManager.GetObject("全校體適能中等以上_含中等_各項目百分比統計表_程式用樣版_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 班級體適能確認單範本1 {
            get {
                object obj = ResourceManager.GetObject("班級體適能確認單範本1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 班級體適能確認單範本113a {
            get {
                object obj = ResourceManager.GetObject("班級體適能確認單範本113a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 班級體適能確認單範本113b {
            get {
                object obj = ResourceManager.GetObject("班級體適能確認單範本113b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 體適能個人證明單_功能變數總表1 {
            get {
                object obj = ResourceManager.GetObject("體適能個人證明單_功能變數總表1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 體適能證明單_範本1 {
            get {
                object obj = ResourceManager.GetObject("體適能證明單_範本1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 體適能資料上傳格式 {
            get {
                object obj = ResourceManager.GetObject("體適能資料上傳格式", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 體適能資料上傳格式_xlsx版_ {
            get {
                object obj = ResourceManager.GetObject("體適能資料上傳格式_xlsx版_", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
